imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.apc
    serializer:
        cache: serializer.mapping.cache.apc

snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
        result_cache:
            client: doctrine_cache
            entity_manager: default
        query_cache:
            client: doctrine_cache
            entity_manager: default

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

nelmio_api_doc:
    sandbox:
        enabled: false

snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine_cache
            entity_manager: default
        result_cache:
            client: doctrine_cache
            entity_manager: default
        query_cache:
            client: doctrine_cache
            entity_manager: default
